GET http://localhost:5000/users

###
POST http:/localhost:5000/users
Content-Type: application/json

{
    "name" : "Nanang Aditya",
    "email" : "admin@gmail.com",
    "password" : "admin123",
    "confPassword" : "admin123"
}