GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJKb2huIERvZSIsImVtYWlsIjoiam9obkBleGFtcGxlLmNvbSIsImlhdCI6MTcxNjI5NjU5NSwiZXhwIjoxNzE2Mjk2NjE1fQ.oZY1NO8nz7iB2gLXznQauERriFnyWabkcQmMLAC8l74

###
POST http:/localhost:5000/users
Content-Type: application/json

{
    "name": "Nanang",
    "email": "member@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "member"
}

###
get http:/localhost:5000/token

###
// update user menggunakan uuid
PATCH http://localhost:5000/users/51165ce4-c6b5-4616-a82e-7cffd9e1db64
Content-Type: application/json

{
    "name": "aditya",
    "email": "superadmin@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "superadmin"
}

###
# Delete user menggunakan uuid
DELETE http://localhost:5000/users/51165ce4-c6b5-4616-a82e-7cffd9e1db64

